common.loader = ${start.home},${start.home}/apps,${start.home}/lib,${start.home}/lib/*.jar

jar.path = 

sdata.path = http://45.117.8.94:88/sgzb/zsggc/gcld_xs_sdata.zip

scan.path = com.reign

startup.class = com.reign.gcld.Startup