# 游戏地址
gcld.game.url = http://45.117.8.94:88/
# 游戏跳转地址
gcld.redirect.url = http://45.117.8.94:88/
# 未预登陆游戏跳转地址
gcld.unprelogin.redirect.url = http://45.117.8.94:88/
# 游戏未登录跳转地址
gcld.unlogin.redirect.url = http://45.117.8.94:88/
# 支付地址
gcld.pay.url = http://45.117.8.94:88/
# 服务器名称
gcld.servername = 37wanS1
# 服务器编号
gcld.serverid = 37
# 查询验证Key
gcld.query.key = ZCDE34D34
# 登录验证Key
gcld.login.key = ZWWAN9801
# 充值验证Key
gcld.pay.key = ZCDE34D32
# 防沉迷页面跳转地址
gcld.addiction.url = http://45.117.8.94:88/
# 防沉迷页面跳转地址
cmwebgame_server_url = http://45.117.8.94:88/
# 是否需要启动防沉迷(0:关闭,1:开启)
gcld.anti.addiction = 0
# 是否可以注册 (0:不可以，1:可以)
gcld.register.user = 1
# 服务器编号(含有S)
gcld.serverids = S37
#初始化玩家最大创建角色数量
gcld.player.maxRoleNum = 1


gcld.yx.ip = 45.117.8.94:88
gcld.limit.yx.ip = 0

gcld.old.user.reward.open = 1

gcld.callback = 1
#充值比例
gcld.pay.bili = 150
#开区多少天后不允许注册，0代表不限制
gcld.allowed.register = 0