#gcld.nation.leagueInfo modify
#Fri Apr 17 06:00:00 CST 2026
gcld.nation.attInfo.wei=13,2;14,2
gcld.open.league.shu=1
gcld.open.league.wu=1
gcld.nation.cityInfo.shu=9
gcld.open.league.wei=1
gcld.nation.attInfo.shu=23,2;24,2
gcld.nation.cityInfo.wei=9
gcld.server.time=1731724200000
gcld.nation.attInfo.wu=33,2;34,2
gcld.nation.leagueInfo=3
gcld.nation.cityInfo.wu=9
